/**
 * Content Freshness: Automated Stale Guide Issue Creator
 *
 * Queries the content-freshness API and creates GitHub issues
 * for guides that haven't been reviewed in a configurable threshold.
 *
 * Usage:
 *   npx tsx scripts/create-stale-guide-issues.ts [--days 90] [--dry-run]
 *
 * Environment:
 *   GITHUB_TOKEN - GitHub personal access token
 *   REPO - GitHub repo (default: pgedeon/sailing-yachts)
 */

const DAYS = parseInt(process.argv.find(a => a.startsWith("--days="))?.split("=")[1] || "90", 10);
const DRY_RUN = process.argv.includes("--dry-run");
const REPO = process.env.REPO || "pgedeon/sailing-yachts";
const BASE_URL = process.env.PLAYWRIGHT_BASE_URL || "https://info.sailboats.fr";

interface StaleArticle {
  id: number;
  slug: string;
  title: string;
  category: string | null;
  lastReviewedAt: string | null;
  reviewStatus: string;
  daysSinceReview: number;
}

interface FreshnessResponse {
  articles: StaleArticle[];
  stats: { total: number; fresh: number; due: number; stale: number; never_reviewed: number };
}

async function main() {
  console.log(`Checking stale guides (threshold: ${DAYS} days)...`);

  const resp = await fetch(`${BASE_URL}/api/content-freshness?days=${DAYS}&limit=50`);
  if (!resp.ok) {
    console.error(`Failed to fetch content freshness: ${resp.status}`);
    process.exit(1);
  }

  const data: FreshnessResponse = await resp.json();

  if (data.articles.length === 0) {
    console.log("✅ No stale guides found. All content is fresh!");
    return;
  }

  console.log(`Found ${data.articles.length} stale guides:`);
  for (const article of data.articles) {
    console.log(`  - "${article.title}" (${article.reviewStatus}, ${article.daysSinceReview} days since review)`);
  }

  if (DRY_RUN) {
    console.log("\n[DRY RUN] Would create GitHub issues for these guides.");
    return;
  }

  // Check for existing stale-guide issues to avoid duplicates
  const existingResp = await fetch(`https://api.github.com/repos/${REPO}/issues?labels=stale-content&state=open&per_page=100`, {
    headers: { Authorization: `token ${process.env.GITHUB_TOKEN}` },
  });
  const existingIssues: { title: string }[] = existingResp.ok ? await existingResp.json() : [];
  const existingTitles = new Set(existingIssues.map(i => i.title));

  let created = 0;
  for (const article of data.articles) {
    const issueTitle = `[Stale Content] Review: ${article.title}`;

    if (existingTitles.has(issueTitle)) {
      console.log(`  ⏭️  Skipping "${article.title}" — issue already exists`);
      continue;
    }

    const body = [
      `## Stale Content Alert`,
      ``,
      `**Guide:** [${article.title}](https://info.sailboats.fr/guides/${article.slug})`,
      `**Category:** ${article.category || "Uncategorized"}`,
      `**Last Reviewed:** ${article.lastReviewedAt ? new Date(article.lastReviewedAt).toLocaleDateString() : "Never"}`,
      `**Days Since Review:** ${article.daysSinceReview}`,
      `**Status:** ${article.reviewStatus}`,
      ``,
      `This guide hasn't been reviewed in ${article.daysSinceReview} days (threshold: ${DAYS} days).`,
      ``,
      `### Actions`,
      `- [ ] Review the guide content for accuracy`,
      `- [ ] Update any outdated information`,
      `- [ ] Update yacht listings if applicable`,
      `- [ ] Mark as reviewed via PUT /api/content-freshness with articleId: ${article.id}`,
      ``,
      `*Auto-generated by content freshness cron.*`,
    ].join("\n");

    const createResp = await fetch(`https://api.github.com/repos/${REPO}/issues`, {
      method: "POST",
      headers: {
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: issueTitle,
        body,
        labels: ["stale-content", "content-review"],
      }),
    });

    if (createResp.ok) {
      const issue = await createResp.json();
      console.log(`  ✅ Created issue #${issue.number}: ${issueTitle}`);
      created++;
    } else {
      const err = await createResp.text();
      console.error(`  ❌ Failed to create issue for "${article.title}": ${createResp.status} ${err}`);
    }
  }

  console.log(`\nDone. Created ${created} issues.`);
}

main().catch(console.error);
